### ISSUE TITLE
CI job "Release-Tarball" no longer works

### ISSUE THREAD

**Issue by auerswal** [schweikert/fping#352]
After merging pull request #350, the automatically triggered CI job "Release-Tarball" failed with the error that it uses a deprecated API version:

> This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v2`. Learn more: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/

![fping-error](https://github.com/user-attachments/assets/3f8013d2-1156-49fe-b757-948d2a3cce3c)

**Comment by gsnw-sebast** [comment]
Pull request #355 was created for this purpose. However, the question is whether the intermediate step should be taken via v3 and we then go to v4 or directly to v4.

Version v4 apparently requires uniqueness in the `name` variable, which can be achieved via `${{ matrix.os }}` in `name`.

**Untested**
```
- uses: actions/upload-artifact@v2
        with:
          name: dist-${{ matrix.os }}
          path: fping-*.tar.gz
```
